name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - run: |
        cd backend
        pip install --upgrade pip
        pip install -r requirements.txt

    - run: |
        cd backend
        black --check .

    - run: |
        cd backend
        ruff check .

    - run: |
        cd backend
        PYTHONPATH=src python -m unittest discover -s tst -v
